### ISSUE TITLE
SDK issues in NodeJs 

### ISSUE THREAD

**Issue by ruggero-balteri** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#115]
Importing this SDK in nodeJS is tricky! 
I want to run `viewer.js` in node, using the `wrtc` package.

By requiring the library `const KVSWebRTC = require("amazon-kinesis-video-streams-webrtc");`
I get this error:

```js
[VIEWER] Starting viewer connection
[VIEWER] Signaling client error:  ReferenceError: WebSocket is not defined
    at SignalingClient.<anonymous> (/XX/XX/node_modules/amazon-kinesis-video-streams-webrtc/lib/SignalingClient.js:107:46)
    at step (XX/XX/node_modules/tslib/tslib.js:141:27)
    at Object.next (XX/XX/node_modules/tslib/tslib.js:122:57)
    at fulfilled (XX/XX/node_modules/tslib/tslib.js:112:62)
```

I think it can be fixed by importing websockets at the beginning of `SignalingClient.js`
```js
var WebSocket = require("ws");
```

but then I get the following error

```js
[VIEWER] Sending ICE candidate
XX/XX/node_modules/amazon-kinesis-video-streams-webrtc/lib/SignalingClient.js:159
        this.sendMessage(MessageType.ICE_CANDIDATE, iceCandidate.toJSON(), recipientClientId);
                                                                 ^

TypeError: iceCandidate.toJSON is not a function
    at SignalingClient.sendIceCandidate (XX/XX/node_modules/amazon-kinesis-video-streams-webrtc/lib/SignalingClient.js:159:66)
    at RTCPeerConnection.<anonymous> (XX/XX/viewer.js:256:32)
    at XX/XX/node_modules/wrtc/lib/eventtarget.js:37:18
    at Set.forEach (<anonymous>)
    at XX/XX/node_modules/wrtc/lib/eventtarget.js:33:15
```

which I think can be fixed in the following way:

```js
this.sendMessage(MessageType.ICE_CANDIDATE, JSON.stringify(iceCandidate), recipientClientId);
```

but then I get an additional error
```js
{"candidate":"candidate:430735571 1 udp 2122260223 192.168.1.102 60702 typ host generation 0 ufrag 7SiN network-id 1 network-cost 50","sdpMid":"0","sdpMLineIndex":0,"foundation":"430735571","component":"rtp","priority":2122260223,"address":"192.168.1.102","protocol":"udp","port":60702,"type":"host","tcpType":null,"relatedAddress":null,"relatedPort":null,"usernameFragment":"7SiN"}
XX/XX/node_modules/amazon-kinesis-video-streams-webrtc/lib/SignalingClient.js:238
        return btoa(JSON.stringify(object));
        ^

ReferenceError: btoa is not defined
    at Function.SignalingClient.serializeJSONObjectAsBase64String (XX/XX/node_modules/amazon-kinesis-video-streams-webrtc/lib/SignalingClient.js:238:9)
    at SignalingClient.sendMessage (XX/XX/node_modules/amazon-kinesis-video-streams-webrtc/lib/SignalingClient.js:174:45)
    at SignalingClient.sendIceCandidate (XX/XX/node_modules/amazon-kinesis-video-streams-webrtc/lib/SignalingClient.js:161:14)
    at RTCPeerConnection.<anonymous> (XX/XX/viewer.js:256:32)
    at XX/XX/node_modules/wrtc/lib/eventtarget.js:37:18
    at Set.forEach (<anonymous>)
    at XX/XX/node_modules/wrtc/lib/eventtarget.js:33:15
```
which I think it could be fixed by
```
SignalingClient.serializeJSONObjectAsBase64String = function (object) {
        return Buffer.from(JSON.stringify(object)).toString('base64')
    };
```
Now 
Still, the MASTER does not receive any IceCandidate messages from the nodeJs VIEWER.

What am I missing?
Thanks!

**Comment by MushMal** [comment]
Have you followed the readme? Which browser are you using? Which versions? The sample should work out-of-the-box.

Please provide more information whether the stock samples work without any modification

**Comment by mentos1386** [comment]
@MushMal I'm having the same issue. Issue appears when code is running on NodeJS. Not on the browser.

Websocket issue is due to NodeJS not having `Websocket` exposed, but it has to be imported from `ws` package.
The second issue with `toJSON` i'm not sure, but it also might be a differenc in NodeJS `webrtc` package compared to browser `webrtc` implementation.

**Comment by ruggero-balteri** [comment]
> @MushMal I'm having the same issue. Issue appears when code is running on NodeJS. Not on the browser.
> 
> Websocket issue is due to NodeJS not having `Websocket` exposed, but it has to be imported from `ws` package.
> 
> My use case for running this inside NodeJS, is that i want to have "infinite" stream of some demo/random video for testing purpose. To "mock" our actual device, that will be later streaming this kind of videos.

My apologies for the late reply! Yes, correct!

**Comment by challenger71498** [comment]
# Solution

@ruggero-balteri In my case, I fixed it by modifying `lib/SignalingClient.js` to:

1. Get `ws` package, as you said.
```javascript
const WebSocket = require('ws');
```
2. Function `atob` and `btoa` will not work on NodeJS. So modify two functions as below:
```javascript
/**
 * Takes the given base64 encoded string and decodes it into a JSON object.
 */
SignalingClient.parseJSONObjectFromBase64String = function (base64EncodedString) {
    return JSON.parse(Buffer.from(base64EncodedString, 'base64').toString('utf-8'));
    // return JSON.parse(atob(base64EncodedString));
};
/**
 * Takes the given JSON object and encodes it into a base64 string.
 */
SignalingClient.serializeJSONObjectAsBase64String = function (object) {
    return  Buffer.from(JSON.stringify(object)).toString('base64');
    // return btoa(JSON.stringify(object));
};
```

# About your error, toJSON()

```
[VIEWER] Sending ICE candidate
XX/XX/node_modules/amazon-kinesis-video-streams-webrtc/lib/SignalingClient.js:159
        this.sendMessage(MessageType.ICE_CANDIDATE, iceCandidate.toJSON(), recipientClientId);
                                                                 ^

TypeError: iceCandidate.toJSON is not a function
    at SignalingClient.sendIceCandidate (XX/XX/node_modules/amazon-kinesis-video-streams-webrtc/lib/SignalingClient.js:159:66)
    at RTCPeerConnection.<anonymous> (XX/XX/viewer.js:256:32)
    at XX/XX/node_modules/wrtc/lib/eventtarget.js:37:18
    at Set.forEach (<anonymous>)
    at XX/XX/node_modules/wrtc/lib/eventtarget.js:33:15
```

The error above occurs because you gave the wrong object I guess. Class `RTCIceCandidate` in `wrtc` npm package does have `toJSON` function. For my case, I used `RTCIceCandidateInit` for communicating with my custom local signaling server, and created a new object on `sendIceCandidate`.

An example would be like:

```typescript
const send = (init: RTCIceCandidateInit) => {
  const candidate = new RTCIceCandidate(init);
  signalingClient.sendIceCandidate(candidate, id);
}
```

# About your solution

```javascript
this.sendMessage(MessageType.ICE_CANDIDATE, JSON.stringify(iceCandidate), recipientClientId);
```

Also, as you look at the script of `SignalingService` inside, `sendIceCandidate` calls `JSON.stringify` function internally. Your code called `JSON.stringify` itself, and also `sendMessage` does, which is basically same as 'stringifying stringified object'.

To work properly, you should give the `RTCIceCandidate` object itself, not stringified version of it.

An example would be like:

```javascript
signalingClient.sendIceCandidate(iceCandidate, id); // NOT JSON.stringify(iceCandidate)!
```

For more insturctions about `JSON.stringify()` and `toJSON()`, see the MDN doc at [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#tojson_behavior).

# Furthermore,

It would be great to use `SignalingService` on node without changing anything by ourselves🤔

Is there any further plan to fix this issue?

**Comment by challenger71498** [comment]
Just realised that,

```
[VIEWER] Sending ICE candidate
XX/XX/node_modules/amazon-kinesis-video-streams-webrtc/lib/SignalingClient.js:159
        this.sendMessage(MessageType.ICE_CANDIDATE, iceCandidate.toJSON(), recipientClientId);
                                                                 ^

TypeError: iceCandidate.toJSON is not a function
    at SignalingClient.sendIceCandidate (XX/XX/node_modules/amazon-kinesis-video-streams-webrtc/lib/SignalingClient.js:159:66)
    at RTCPeerConnection.<anonymous> (XX/XX/viewer.js:256:32)
    at XX/XX/node_modules/wrtc/lib/eventtarget.js:37:18
    at Set.forEach (<anonymous>)
    at XX/XX/node_modules/wrtc/lib/eventtarget.js:33:15
```

this error might be caused by `node-webrtc` package.

I encountered same error as you even I put a solid RTCIceCandidate object.

So i dug deeper inside the package, and found that `RTCIceCandidate` on `node-webrtc` does not have `toJSON` function itself.

Temporarily you can fix this issue by creating your own `toJSON` function at `node_modules/wrtc/lib/icecandidate.js`, such as below:

```
this.toJSON = () => {
  const { candidate, sdpMid, sdpMLineIndex, usernameFragment } = this;
  let json = {
    candidate,
    sdpMid,
    sdpMLineIndex
  };

  if (usernameFragment) {
    json.usernameFragment = usernameFragment;
  }

  return json;
}
```

I created a PR on `node-webrtc` tho, so if they accept it, your issue may be solved via update.

**Comment by Snapu** [comment]
+1

The README gives the impression that it works with NodeJS but it clearly is not.

**Comment by sirknightj** [comment]
Should be fixed in `develop` branch

**Comment by sirknightj** [comment]
This has been merged into the `master` branch. Please use the latest version: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-js/releases/tag/v2.2.0
