### ISSUE TITLE
Example does not work

### ISSUE THREAD

**Issue by radiantone** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#24]
I put in my AWS keys and I provide a (made up) channel name, and I start the master.
It throws errors in javascript console.

What am I supposed to see with this example? Do I start the master and it will broadcast my webcam video to the channel and then I can view it from the viewer mode? It's not clear what the example should do. I just see two black screens.

aws-sdk-2.585.0.min.js:70 POST https://kinesisvideo.us-east-1.amazonaws.com/describeSignalingChannel 404 (Not Found)

aws-sdk-2.585.0.min.js:70 Uncaught (in promise) ResourceNotFoundException: The requested channel is not found or not active.
    at Object.a [as extractError] (https://sdk.amazonaws.com/js/aws-sdk-2.585.0.min.js:70:29682)
    at constructor.o (https://sdk.amazonaws.com/js/aws-sdk-2.585.0.min.js:71:2967)
    at constructor.callListeners (https://sdk.amazonaws.com/js/aws-sdk-2.585.0.min.js:71:29696)
    at constructor.emit (https://sdk.amazonaws.com/js/aws-sdk-2.585.0.min.js:71:29407)
    at constructor.emitEvent (https://sdk.amazonaws.com/js/aws-sdk-2.585.0.min.js:71:15204)
    at constructor.e (https://sdk.amazonaws.com/js/aws-sdk-2.585.0.min.js:71:10846)
    at i.runTo (https://sdk.amazonaws.com/js/aws-sdk-2.585.0.min.js:73:18442)
    at https://sdk.amazonaws.com/js/aws-sdk-2.585.0.min.js:73:18647
    at constructor.<anonymous> (https://sdk.amazonaws.com/js/aws-sdk-2.585.0.min.js:71:11056)
    at constructor.<anonymous> (https://sdk.amazonaws.com/js/aws-sdk-2.585.0.min.js:71:15259)

**Comment by radiantone** [comment]
I see the reason. I didn't notice in the README where it said you have to first click Create Channel, then run Master. Also, in order for the viewer to work from remote machine you have to enable --https in the webpack dev server and use https in URL. Also, you have to use --host 0.0.0.0

in package.json

"develop": "webpack-dev-server  --https --host 0.0.0.0 --config webpack.dev.config.js",
